### ISSUE TITLE
Error when trying to jump to the WP function

### ISSUE THREAD

**Issue by simonwheatley** [Gipetto/wordpress.tmbundle#6] opened 2010-03-30 17:34 UTC
When I try to "Go to function" I'm getting the following error:

```
/tmp/temp_textmate.Inu6cY:in `require': no such file to load -- /Users/simon/Library/Application Support/TextMate/Bundles/WordPress.tmbundle/Support/common.rb (LoadError) from /tmp/temp_textmate.Inu6cY:2
```

Since this morning, when it was working, I've edited the plugin_head snippet and added my own plugin_base snippet.

If I delete and reinstall, it starts working. If I re-add the snippets, it starts working!

Any ideas?

Thanks in advance.

S

**Comment by simonwheatley** [comment] 2010-03-30 17:57
I think this error is caused by editing the WordPress bundle, then closing the Bundle Editor... until the editor is closed it works, afterwards it doesn't, even if you make changes before closing the editor and see the changes in action.

Hope this helps.

S

**Comment by Gipetto** [comment] 2010-04-11 08:18
Not sure if you're still having this issue or not, but I haven't been able to reproduce this. Are you still having this issue? If so, can you "break" it and send me a copy of the broken bundle?

**Comment by simonwheatley** [comment] 2010-04-12 08:12
Here you go: http://dl.dropbox.com/u/72676/WordPress.tmbundle.zip

What I did: Edit the bundle, close the bundle editor.

Thanks for looking into this.

Best regards,

Simon

**Comment by simonwheatley** [comment] 2010-04-26 10:01
I thought I remembered you had an issue with the download I posted above, but I can't find the comment/email... did the broken bundle "work" for you?

S

**Comment by Gipetto** [comment] 2010-05-21 18:17
Sorry I'm just now getting back to this. The broken bundle was in fact broken. Very broken. It was missing everything but you're added snippets. 

I can't reproduce the problem, either.

**Comment by Gipetto** [comment] 2011-02-16 20:42
Closing. Cannot reproduce.

**Closed as completed by Gipetto** 2011-02-16 20:42 UTC
